name: Deploy n8n to Fly.io
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions@v1
        with:
          args: "deploy"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Importar workflows
        run: |
          fly ssh console -C "sh -c '/usr/local/bin/sync_workflows.sh import'"
